### ISSUE TITLE
github release 0.5.0 missing artifacts

### ISSUE THREAD

**Issue by intrand** [nikolaj-a/pf2e-action-browser#11]
You've probably noticed, but I thought I'd mention it. Looks like the workflow changed to enable automated release notes. Maybe that broke it / requires more parameters? Not sure without really digging in.

**Comment by nikolaj-a** [comment]
I didn’t notice! Is it better now?

**Comment by intrand** [comment]
![image](https://github.com/user-attachments/assets/69c1e201-f2da-40e7-a780-882006697b74)

Golden! Thank you!
